### ISSUE TITLE
Add missing letters from title

### ISSUE THREAD

**Issue by Khimit** [Canvasbird/canvasboard#302]
The letters **"r"** and **"d"** from the title **Canvasboard** are not there in the **login** and **sign up** pages both.
![Canva1](https://user-images.githubusercontent.com/46605529/103179637-0b8c7680-48b4-11eb-927f-d16d056030d5.PNG)
![Canva2](https://user-images.githubusercontent.com/46605529/103179642-13e4b180-48b4-11eb-985e-4508136ac2e2.PNG)

 **Need to be corrected.**

**Comment by Khimit** [comment]
I would like to work on this issue.
Can you assign this to me??

**Comment by DevoAbhi** [comment]
Can you please explain to me the issue? 
Because on my side, the names are appearing properly.

The Screenshots for the same are :

![canva-login](https://user-images.githubusercontent.com/54373853/103180735-8fe3f700-48be-11eb-8f25-89b0263bd969.png)
![canva-signup](https://user-images.githubusercontent.com/54373853/103180736-92465100-48be-11eb-99a0-fd9a7b0771ce.png)


![canva-signup](https://user-images.githubusercontent.com/54373853/103180737-9a05f580-48be-11eb-909a-5a4f7ad59bd4.png)
![canva-login](https://user-images.githubusercontent.com/54373853/103180738-9bcfb900-48be-11eb-8f14-24ba973bb8a3.png)

**Comment by DevoAbhi** [comment]
Can you please explain me the issue?
Because on my end the letters are appearing properly.

The Screenshots for the same are :

![canva-login](https://user-images.githubusercontent.com/54373853/103180755-e3564500-48be-11eb-8744-80532b232983.png)


![canva-signup](https://user-images.githubusercontent.com/54373853/103180760-f10bca80-48be-11eb-849d-962baf33436e.png)

**Comment by Khimit** [comment]
Ohkk,
 So I think problem is from my end only
